- name: Configure
  become: true
  tags: config
  block:
    - name: Create installation directory
      ansible.builtin.file:
        path: '/srv/monitoring'
        state: directory
        mode: '0755'
    - name: Copy Compose file
      ansible.builtin.copy:
        src: 'compose.yaml'
        dest: '/srv/monitoring/'
        mode: '0644'
    - name: Configure services
      ansible.builtin.template:
        src: '{{ item }}'
        dest: '/srv/monitoring/{{ item.rsplit(".", 1)[0] | basename }}'
        mode: '0644'
      loop:
        - prometheus.yaml.j2
        - Caddyfile.j2
        - heplify-server.env.j2
    - name: Provision grafana datasource
      ansible.builtin.copy:
        src: 'provisioning'
        dest: '/srv/monitoring/'
        mode: '0644'
    - name: Set grafana admin password
      ansible.builtin.template:
        src: 'grafana.ini.j2'
        dest: '/srv/monitoring/grafana.ini'
        mode: '0644'
        force: false
      notify: Print grafana password
    - name: Start services
      community.docker.docker_compose_v2:
        project_src: '/srv/monitoring'
        state: present
