- name: Prepare
  become: true
  tags: pre
  block:
    - name: Add kamailio repository
      ansible.builtin.deb822_repository:
        name: kamailio
        suites: '{{ ansible_lsb.codename }}'
        components: main
        uris: 'http://deb.kamailio.org/{{ kamailio_version }}'
        signed_by: 'https://deb.kamailio.org/kamailiodebkey.gpg'
    - name: Install rtpengine repository key
      ansible.builtin.apt:
        deb: 'https://rtpengine.dfx.at/latest/pool/main/r/rtpengine-dfx-repo-keyring/rtpengine-dfx-repo-keyring_1.0_all.deb'
    - name: Add rtpengine repository
      ansible.builtin.deb822_repository:
        name: rtpengine
        suites: '{{ ansible_lsb.codename }}'
        components: main
        uris: 'https://rtpengine.dfx.at/{{ kamailio_rtpengine_version }}'
        signed_by: /usr/share/keyrings/dfx.at-rtpengine-archive-keyring.gpg
- name: Install
  become: true
  tags: install
  block:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - kamailio
          - kamailio-tls-modules
          - kamailio-lua-modules
          - kamailio-json-modules
          - rtpengine
          - liblua5.4-0
          - linux-headers-generic
- name: Configure
  become: true
  tags: config
  block:
    - name: Enable rtpengine service
      ansible.builtin.systemd_service:
        name: rtpengine
        enabled: true
        state: started
    - name: Copy kamailio routing script
      ansible.builtin.copy:
        src: 'kamailio.lua'
        dest: '/etc/kamailio/'
        mode: '0644'
    - name: Copy kamailio config files
      ansible.builtin.template:
        src: '{{ item }}'
        dest: '/etc/kamailio/{{ item.rsplit(".", 1)[0] | basename }}'
        mode: '0644'
      loop:
        - kamailio.cfg.j2
        - dispatcher.list.j2
    - name: Enable kamailio service
      ansible.builtin.systemd_service:
        name: kamailio
        enabled: true
        state: started
