name: monitoring
services:
  proxy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
  hepserver:
    image: ghcr.io/sipcapture/heplify-server
    env_file: [heplify-server.env]
    command: [./heplify-server]
    ports:
      - "9060:9060/udp"
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
volumes:
  caddy-data:
  grafana-data:
  prometheus-data:
